repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    -   id: reorder-python-imports
        types: [python]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.4.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
        types: [rst]
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    -   id: black
        types: [python]
        args: [--line-length=79]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        types: [python]
        additional_dependencies: [
            flake8-bugbear, flake8-builtins, flake8-comprehensions, flake8-docstrings,
            flake8-eradicate, flake8-print, flake8-rst-docstrings, flake8-todo,
            pep8-naming, pydocstyle==3.0.0,
        ]
        args: [--ignore=E203, --exclude=__init__.py causaltree.py simulate_data.py tests/*]
-   repo: https://github.com/PyCQA/doc8
    rev: 0.8.1rc2
    hooks:
        -   id: doc8
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest -v
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false
