language: python

python:
  - 3.7

bundler_args: --retry 3

install:
  - sudo apt-get update
  - ./utils/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate causal-forest


script:
  - source .envrc
    #- travis_wait python utils/travis_runner.py
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=causal-forest --pyargs causal-forest


 after_success:
   - codecov
